blank_issues_enabled: true
contact_links:
  - name: 💬 Preguntas generales / Discusiones
    url: https://github.com
    about: Si tienes dudas conceptuales o ideas que no son tareas concretas, abre una discusión.