name: Deploy por FTP

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama principal se llama así

jobs:
  web-deploy:
    name: Subir archivos al servidor
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código más reciente
        uses: actions/checkout@v4

      - name: Subir archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: visualizador_rutas/